namespace ReleaseOrchestrator.Pwa.Models;

public record ReleasePlanDto(
    Guid Id, string Name, string Version, bool IsActive, bool AutoGenerated,
    DateTime CreatedAt, DateTime UpdatedAt, List<ReleaseStageDto> Stages);

public record ReleaseStageDto(
    Guid Id, int Sequence, string? Name, bool IsManualOverride,
    List<StageItemDto> Items);

public record StageItemDto(
    Guid Id, Guid MergeRequestId, bool ManualInclusion,
    string MrExternalId, string MrSourceBranch, string MrTargetBranch,
    string RepositoryName, string? TaskExternalId, string MrStatus);

public record VcsConnectionDto(Guid Id, string Name, string VcsType, string ApiUrl, string? ConnectionName = null);

public record TrackerConnectionDto(Guid Id, string Name, string TrackerType, string ApiUrl, string? OrgId);

public record RepositoryDto(Guid Id, string Name, string ExternalId, Guid ConnectionId, string ConnectionName);

public record StackDto(Guid Id, string Name);

public record MrDto(
    Guid Id, string ExternalId, string SourceBranch, string TargetBranch,
    string Status, DateTime CreatedAt, Guid RepositoryId,
    string RepositoryName, string ConnectionName, string? TaskExternalId);

public record PagedResult<T>(int Total, int Page, int PageSize, List<T> Items);

public record PermissionClaimDto(Guid Id, string Name);
public record GroupMappingDto(Guid Id, string AdGroupSid, string ClaimName);
