using ReleaseOrchestrator.Infrastructure.Persistence.Models;

namespace ReleaseOrchestrator.Infrastructure.Archive;

/// <summary>
/// Serialised into <see cref="Entities.ArchivedReleasePlan.PlanJson"/>. Items carry the merge
/// request's identifying fields rather than only its id, because the merge requests are
/// archived into a different table on their own schedule and a plan must stay readable on its own.
/// </summary>
internal sealed record PlanSnapshot(
    Guid Id,
    string Name,
    string Version,
    bool AutoGenerated,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    string? YamlHash,
    string? ConflictsJson,
    IReadOnlyList<StageSnapshot> Stages)
{
    public static PlanSnapshot From(ReleasePlan p) => new(
        p.Id,
        p.Name,
        p.Version,
        p.AutoGenerated,
        p.CreatedAt,
        p.UpdatedAt,
        p.YamlHash,
        p.ConflictsJson,
        [.. p.Stages.OrderBy(s => s.Sequence).Select(StageSnapshot.From)]);
}

internal sealed record StageSnapshot(
    Guid Id,
    int Sequence,
    string? Name,
    bool IsManualOverride,
    IReadOnlyList<StageItemSnapshot> Items)
{
    public static StageSnapshot From(ReleaseStage s) => new(
        s.Id,
        s.Sequence,
        s.Name,
        s.IsManualOverride,
        [.. s.Items.Select(StageItemSnapshot.From)]);
}

internal sealed record StageItemSnapshot(
    Guid MergeRequestId,
    string MergeRequestExternalId,
    string RepositoryName,
    string SourceBranch,
    string TargetBranch,
    string? TaskExternalId,
    bool ManualInclusion)
{
    public static StageItemSnapshot From(StageItem i) => new(
        i.MergeRequestId,
        i.MergeRequest.ExternalId,
        i.MergeRequest.Repository.Name,
        i.MergeRequest.SourceBranch,
        i.MergeRequest.TargetBranch,
        i.MergeRequest.Task?.ExternalId,
        i.ManualInclusion);
}
