// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReleaseOrchestrator.Infrastructure.Persistence;

#nullable disable

namespace ReleaseOrchestrator.Migrations.MsSql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718135903_AddRolloutPlanAggregate")]
    partial class AddRolloutPlanAggregate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.DeploymentEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Key" }, "IX_DeploymentEnvironment_Key")
                        .IsUnique();

                    b.ToTable("DeploymentEnvironments");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.GroupPermissionMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdGroupSid")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PermissionClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionClaimId");

                    b.HasIndex(new[] { "AdGroupSid", "PermissionClaimId" }, "IX_GroupPermissionMapping_AdGroupSid_PermissionClaimId")
                        .IsUnique();

                    b.ToTable("GroupPermissionMappings");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsStatusManual")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TargetBranch")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TaskExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClosedAt" }, "IX_MergeRequest_ClosedAt");

                    b.HasIndex(new[] { "MergedAt" }, "IX_MergeRequest_MergedAt");

                    b.HasIndex(new[] { "RepositoryId", "ExternalId" }, "IX_MergeRequest_RepositoryId_ExternalId")
                        .IsUnique();

                    b.HasIndex(new[] { "RepositoryId", "Status" }, "IX_MergeRequest_RepositoryId_Status");

                    b.HasIndex(new[] { "Status" }, "IX_MergeRequest_Status");

                    b.HasIndex(new[] { "TaskExternalId" }, "IX_MergeRequest_TaskExternalId");

                    b.HasIndex(new[] { "TaskId" }, "IX_MergeRequest_TaskId");

                    b.ToTable("MergeRequests");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PermissionClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PermissionClaims");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeployStrategyKeyOverride")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IntraTaskOrder")
                        .HasColumnType("int");

                    b.Property<bool>("ManualInclusion")
                        .HasColumnType("bit");

                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlanTaskNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MergeRequestId" }, "IX_PlanItem_MergeRequestId");

                    b.HasIndex(new[] { "PlanTaskNodeId", "MergeRequestId" }, "IX_PlanItem_Node_Mr")
                        .IsUnique();

                    b.ToTable("PlanItems");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolloutPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RolloutPlanId");

                    b.ToTable("PlanOverrides");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanTaskNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolloutPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex(new[] { "RolloutPlanId", "TaskId" }, "IX_PlanTaskNode_Plan_Task")
                        .IsUnique();

                    b.ToTable("PlanTaskNodes");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.ReleasePlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AutoGenerated")
                        .HasColumnType("bit");

                    b.Property<string>("ConflictsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("SnapshotStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YamlHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("IX_ReleasePlan_IsActive")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_ReleasePlan_CreatedAt");

                    b.ToTable("ReleasePlans");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.ReleaseStage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsManualOverride")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.ToTable("ReleaseStages");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("TrackerConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrackerConnectionId");

                    b.HasIndex(new[] { "ConnectionId", "ExternalId" }, "IX_Repository_ConnectionId_ExternalId")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RepositoryDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromRepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToRepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToRepositoryId");

                    b.HasIndex(new[] { "FromRepositoryId", "ToRepositoryId" }, "IX_RepositoryDependency_From_To")
                        .IsUnique();

                    b.ToTable("RepositoryDependencies");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RepositoryStack", b =>
                {
                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RepositoryId", "StackId");

                    b.HasIndex("StackId");

                    b.ToTable("RepositoryStacks");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConflictsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("SnapshotStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YamlHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TargetTaskId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolloutPlan_TargetTaskId_Active")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_RolloutPlan_CreatedAt");

                    b.ToTable("RolloutPlans");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Stack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Stacks");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.StackDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromStackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToStackId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromStackId");

                    b.HasIndex("ToStackId");

                    b.ToTable("StackDependencies");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.StageItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ManualInclusion")
                        .HasColumnType("bit");

                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.HasIndex(new[] { "MergeRequestId" }, "IX_StageItem_MergeRequestId");

                    b.ToTable("StageItems");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DependentTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DependsOnTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnTaskId");

                    b.HasIndex(new[] { "DependentTaskId", "DependsOnTaskId" }, "IX_TaskDependency_Dependent_DependsOn")
                        .IsUnique();

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TrackerConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClosedAt" }, "IX_TaskItem_ClosedAt");

                    b.HasIndex(new[] { "ExternalId" }, "IX_TaskItem_ExternalId");

                    b.HasIndex(new[] { "TrackerConnectionId", "ExternalId" }, "IX_TaskItem_TrackerConnectionId_ExternalId")
                        .IsUnique();

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TrackerConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProviderSettingsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TrackerConnections");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.UserPermissionOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionClaimId");

                    b.HasIndex(new[] { "UserId", "PermissionClaimId" }, "IX_UserPermissionOverride_UserId_PermissionClaimId")
                        .IsUnique();

                    b.ToTable("UserPermissionOverrides");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.VcsConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReadyForDeployLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_VcsConnection_Name")
                        .IsUnique();

                    b.ToTable("VcsConnections");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.GroupPermissionMapping", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.PermissionClaim", "PermissionClaim")
                        .WithMany("GroupMappings")
                        .HasForeignKey("PermissionClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionClaim");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", "Repository")
                        .WithMany("MergeRequests")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "Task")
                        .WithMany("MergeRequests")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Repository");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanItem", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanTaskNode", "PlanTaskNode")
                        .WithMany("Items")
                        .HasForeignKey("PlanTaskNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MergeRequest");

                    b.Navigation("PlanTaskNode");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanOverride", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", "RolloutPlan")
                        .WithMany("Overrides")
                        .HasForeignKey("RolloutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolloutPlan");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanTaskNode", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", "RolloutPlan")
                        .WithMany("Nodes")
                        .HasForeignKey("RolloutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RolloutPlan");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.ReleaseStage", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.ReleasePlan", "Plan")
                        .WithMany("Stages")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.VcsConnection", "Connection")
                        .WithMany("Repositories")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TrackerConnection", "TrackerConnection")
                        .WithMany("Repositories")
                        .HasForeignKey("TrackerConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Connection");

                    b.Navigation("TrackerConnection");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RepositoryDependency", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", "FromRepository")
                        .WithMany("DependsOn")
                        .HasForeignKey("FromRepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", "ToRepository")
                        .WithMany("RequiredBy")
                        .HasForeignKey("ToRepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromRepository");

                    b.Navigation("ToRepository");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RepositoryStack", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", "Repository")
                        .WithMany("RepositoryStacks")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Stack", "Stack")
                        .WithMany("RepositoryStacks")
                        .HasForeignKey("StackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("Stack");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "TargetTask")
                        .WithMany()
                        .HasForeignKey("TargetTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TargetTask");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.StackDependency", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Stack", "FromStack")
                        .WithMany("DependentOn")
                        .HasForeignKey("FromStackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Stack", "ToStack")
                        .WithMany("RequiredBy")
                        .HasForeignKey("ToStackId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStack");

                    b.Navigation("ToStack");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.StageItem", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", "MergeRequest")
                        .WithMany("StageItems")
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.ReleaseStage", "Stage")
                        .WithMany("Items")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MergeRequest");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskDependency", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "DependentTask")
                        .WithMany("Dependencies")
                        .HasForeignKey("DependentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "DependsOnTask")
                        .WithMany("Dependents")
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependentTask");

                    b.Navigation("DependsOnTask");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TrackerConnection", "TrackerConnection")
                        .WithMany("Tasks")
                        .HasForeignKey("TrackerConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrackerConnection");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.UserPermissionOverride", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.PermissionClaim", "PermissionClaim")
                        .WithMany("UserOverrides")
                        .HasForeignKey("PermissionClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionClaim");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", b =>
                {
                    b.Navigation("StageItems");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PermissionClaim", b =>
                {
                    b.Navigation("GroupMappings");

                    b.Navigation("UserOverrides");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanTaskNode", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.ReleasePlan", b =>
                {
                    b.Navigation("Stages");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.ReleaseStage", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", b =>
                {
                    b.Navigation("DependsOn");

                    b.Navigation("MergeRequests");

                    b.Navigation("RepositoryStacks");

                    b.Navigation("RequiredBy");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("Overrides");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Stack", b =>
                {
                    b.Navigation("DependentOn");

                    b.Navigation("RepositoryStacks");

                    b.Navigation("RequiredBy");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");

                    b.Navigation("MergeRequests");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TrackerConnection", b =>
                {
                    b.Navigation("Repositories");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.VcsConnection", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
