// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReleaseOrchestrator.Infrastructure.Persistence;

#nullable disable

namespace ReleaseOrchestrator.Migrations.MsSql.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260718225740_RetireGlobalPlanAndStacks")]
    partial class RetireGlobalPlanAndStacks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xml")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.ActionBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("bit");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EventType" }, "IX_ActionBinding_EventType");

                    b.ToTable("ActionBindings");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.DeploymentEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Key" }, "IX_DeploymentEnvironment_Key")
                        .IsUnique();

                    b.ToTable("DeploymentEnvironments");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.GroupPermissionMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdGroupSid")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("PermissionClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionClaimId");

                    b.HasIndex(new[] { "AdGroupSid", "PermissionClaimId" }, "IX_GroupPermissionMapping_AdGroupSid_PermissionClaimId")
                        .IsUnique();

                    b.ToTable("GroupPermissionMappings");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsStatusManual")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TargetBranch")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TaskExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClosedAt" }, "IX_MergeRequest_ClosedAt");

                    b.HasIndex(new[] { "MergedAt" }, "IX_MergeRequest_MergedAt");

                    b.HasIndex(new[] { "RepositoryId", "ExternalId" }, "IX_MergeRequest_RepositoryId_ExternalId")
                        .IsUnique();

                    b.HasIndex(new[] { "RepositoryId", "Status" }, "IX_MergeRequest_RepositoryId_Status");

                    b.HasIndex(new[] { "Status" }, "IX_MergeRequest_Status");

                    b.HasIndex(new[] { "TaskExternalId" }, "IX_MergeRequest_TaskExternalId");

                    b.HasIndex(new[] { "TaskId" }, "IX_MergeRequest_TaskId");

                    b.ToTable("MergeRequests");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MrDeployClaim", b =>
                {
                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OwnerRolloutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("MergeRequestId", "EnvironmentId");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("MrDeployClaims");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MrDeploymentState", b =>
                {
                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MergeRequestId", "EnvironmentId");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("MrDeploymentStates");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PermissionClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PermissionClaims");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeployStrategyKeyOverride")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IntraTaskOrder")
                        .HasColumnType("int");

                    b.Property<bool>("ManualInclusion")
                        .HasColumnType("bit");

                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlanTaskNodeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MergeRequestId" }, "IX_PlanItem_MergeRequestId");

                    b.HasIndex(new[] { "PlanTaskNodeId", "MergeRequestId" }, "IX_PlanItem_Node_Mr")
                        .IsUnique();

                    b.ToTable("PlanItems");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolloutPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RolloutPlanId");

                    b.ToTable("PlanOverrides");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanTaskNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolloutPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex(new[] { "RolloutPlanId", "TaskId" }, "IX_PlanTaskNode_Plan_Task")
                        .IsUnique();

                    b.ToTable("PlanTaskNodes");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.ProcessedEvent", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EventId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Source", "EventId");

                    b.ToTable("ProcessedEvents");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeployStrategyKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DeployStrategySettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid?>("TrackerConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TrackerConnectionId");

                    b.HasIndex(new[] { "ConnectionId", "ExternalId" }, "IX_Repository_ConnectionId_ExternalId")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RepositoryDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FromRepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ToRepositoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ToRepositoryId");

                    b.HasIndex(new[] { "FromRepositoryId", "ToRepositoryId" }, "IX_RepositoryDependency_From_To")
                        .IsUnique();

                    b.ToTable("RepositoryDependencies");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Rollout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LaunchedByOid")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PlanSnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolloutPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("RolloutPlanId");

                    b.HasIndex(new[] { "IdempotencyKey" }, "IX_Rollout_IdempotencyKey")
                        .IsUnique();

                    b.HasIndex(new[] { "TargetTaskId" }, "IX_Rollout_TargetTaskId");

                    b.ToTable("Rollouts");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolloutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RolloutId");

                    b.ToTable("RolloutEvents");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConflictsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("SnapshotStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TargetTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("YamlHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TargetTaskId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolloutPlan_TargetTaskId_Active")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_RolloutPlan_CreatedAt");

                    b.ToTable("RolloutPlans");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("DeployStrategyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MergeShaAtSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RolloutId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Wave")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MergeRequestId");

                    b.HasIndex("TaskId");

                    b.HasIndex(new[] { "RolloutId", "MergeRequestId" }, "IX_RolloutStep_Rollout_Mr")
                        .IsUnique();

                    b.ToTable("RolloutSteps");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutStepAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("RolloutStepId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RolloutStepId");

                    b.ToTable("RolloutStepAttempts");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DependentTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DependsOnTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnTaskId");

                    b.HasIndex(new[] { "DependentTaskId", "DependsOnTaskId" }, "IX_TaskDependency_Dependent_DependsOn")
                        .IsUnique();

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("TrackerConnectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClosedAt" }, "IX_TaskItem_ClosedAt");

                    b.HasIndex(new[] { "ExternalId" }, "IX_TaskItem_ExternalId");

                    b.HasIndex(new[] { "TrackerConnectionId", "ExternalId" }, "IX_TaskItem_TrackerConnectionId_ExternalId")
                        .IsUnique();

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TrackerConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProviderSettingsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TrackerConnections");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.UserPermissionOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionClaimId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionClaimId");

                    b.HasIndex(new[] { "UserId", "PermissionClaimId" }, "IX_UserPermissionOverride_UserId_PermissionClaimId")
                        .IsUnique();

                    b.ToTable("UserPermissionOverrides");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.VcsConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte[]>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("IngestionMode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("PollIntervalSeconds")
                        .HasColumnType("int");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReadyForDeployLabel")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_VcsConnection_Name")
                        .IsUnique();

                    b.ToTable("VcsConnections");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.GroupPermissionMapping", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.PermissionClaim", "PermissionClaim")
                        .WithMany("GroupMappings")
                        .HasForeignKey("PermissionClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionClaim");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", "Repository")
                        .WithMany("MergeRequests")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "Task")
                        .WithMany("MergeRequests")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Repository");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MrDeployClaim", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.DeploymentEnvironment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Environment");

                    b.Navigation("MergeRequest");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MrDeploymentState", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.DeploymentEnvironment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Environment");

                    b.Navigation("MergeRequest");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanItem", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanTaskNode", "PlanTaskNode")
                        .WithMany("Items")
                        .HasForeignKey("PlanTaskNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MergeRequest");

                    b.Navigation("PlanTaskNode");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanOverride", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", "RolloutPlan")
                        .WithMany("Overrides")
                        .HasForeignKey("RolloutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolloutPlan");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanTaskNode", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", "RolloutPlan")
                        .WithMany("Nodes")
                        .HasForeignKey("RolloutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RolloutPlan");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.VcsConnection", "Connection")
                        .WithMany("Repositories")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TrackerConnection", "TrackerConnection")
                        .WithMany("Repositories")
                        .HasForeignKey("TrackerConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Connection");

                    b.Navigation("TrackerConnection");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RepositoryDependency", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", "FromRepository")
                        .WithMany("DependsOn")
                        .HasForeignKey("FromRepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", "ToRepository")
                        .WithMany("RequiredBy")
                        .HasForeignKey("ToRepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromRepository");

                    b.Navigation("ToRepository");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Rollout", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.DeploymentEnvironment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", "RolloutPlan")
                        .WithMany()
                        .HasForeignKey("RolloutPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "TargetTask")
                        .WithMany()
                        .HasForeignKey("TargetTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Environment");

                    b.Navigation("RolloutPlan");

                    b.Navigation("TargetTask");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutEvent", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Rollout", "Rollout")
                        .WithMany()
                        .HasForeignKey("RolloutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rollout");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "TargetTask")
                        .WithMany()
                        .HasForeignKey("TargetTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TargetTask");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutStep", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Rollout", "Rollout")
                        .WithMany("Steps")
                        .HasForeignKey("RolloutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MergeRequest");

                    b.Navigation("Rollout");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutStepAttempt", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutStep", "RolloutStep")
                        .WithMany("Attempts")
                        .HasForeignKey("RolloutStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolloutStep");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskDependency", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "DependentTask")
                        .WithMany("Dependencies")
                        .HasForeignKey("DependentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "DependsOnTask")
                        .WithMany("Dependents")
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependentTask");

                    b.Navigation("DependsOnTask");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TrackerConnection", "TrackerConnection")
                        .WithMany("Tasks")
                        .HasForeignKey("TrackerConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrackerConnection");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.UserPermissionOverride", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.PermissionClaim", "PermissionClaim")
                        .WithMany("UserOverrides")
                        .HasForeignKey("PermissionClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionClaim");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PermissionClaim", b =>
                {
                    b.Navigation("GroupMappings");

                    b.Navigation("UserOverrides");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanTaskNode", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", b =>
                {
                    b.Navigation("DependsOn");

                    b.Navigation("MergeRequests");

                    b.Navigation("RequiredBy");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Rollout", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("Overrides");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutStep", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", b =>
                {
                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");

                    b.Navigation("MergeRequests");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TrackerConnection", b =>
                {
                    b.Navigation("Repositories");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.VcsConnection", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
