using Microsoft.EntityFrameworkCore;
using ReleaseOrchestrator.Application.Exceptions;
using ReleaseOrchestrator.Core.Enums;
using Xunit;

namespace ReleaseOrchestrator.UnitTests.ReleasePlanning;

/// <summary>
/// YAML import is the one place a release plan arrives from outside, written by hand, and it is
/// trusted enough to outrank the algorithm's own. Everything it accepts, it deploys.
/// </summary>
public sealed class ReleasePlanImportTests : PlannerTestBase
{
    private static string Yaml(params string[] stages) =>
        $"""
         release_plan:
           name: manual
           version: "1"
           stages:
         {string.Join("\n", stages)}
         """;

    /// <summary>One stage holding the given <c>mr_id</c>s, indented to sit under <c>stages:</c>.</summary>
    private static string Stage(int seq, params string[] mrIds) =>
        $"    - seq: {seq}\n      items:\n"
        + string.Join("\n", mrIds.Select(id => $"        - mr_id: {id}"));

    [Fact]
    public async Task AnImportedPlanBecomesActiveAndDeactivatesTheAutomaticOne()
    {
        var repo = AddRepository("api");
        AddMergeRequest(repo, externalId: "10");
        await Db.SaveChangesAsync(Ct);

        var planner = Planner();
        var auto = await planner.RecalculateAsync(Ct);

        var imported = await planner.ImportFromYamlAsync(Yaml(Stage(1, "vcs:group/api!10")), ct: Ct);

        Assert.True(imported.IsActive);
        Assert.False(imported.AutoGenerated);
        var active = Assert.Single(await Db.ReleasePlans.Where(p => p.IsActive).ToListAsync(Ct));
        Assert.Equal(imported.Id, active.Id);

        // AsNoTracking, deliberately: the deactivation runs as ExecuteUpdate, which writes past the
        // change tracker. A tracked read here answers from the stale cached entity and reports the
        // old plan as still active — the test would be asking EF what it remembers, not the database.
        var previous = await Db.ReleasePlans.AsNoTracking().FirstAsync(p => p.Id == auto.Id, Ct);
        Assert.False(previous.IsActive);
    }

    /// <summary>
    /// The order in the file is the order that deploys — the importer must not re-sort by anything
    /// else, and a document listing its stages out of order is still a valid document.
    /// </summary>
    [Fact]
    public async Task StagesKeepTheSequenceGivenInTheDocumentRegardlessOfDocumentOrder()
    {
        var repo = AddRepository("api");
        var first = AddMergeRequest(repo, externalId: "10");
        var second = AddMergeRequest(repo, externalId: "20");
        await Db.SaveChangesAsync(Ct);

        var plan = await Planner().ImportFromYamlAsync(
            Yaml(Stage(2, "vcs:group/api!20"), Stage(1, "vcs:group/api!10")), ct: Ct);

        Assert.Equal([first.Id], StageItems(plan, 1));
        Assert.Equal([second.Id], StageItems(plan, 2));
    }

    /// <summary>
    /// An operator may deploy against a hard stack link — a release sometimes has to — so the
    /// import is accepted. What it may not do is come out looking clean: the violation is recorded
    /// on the plan, naming both sides, because a plan nobody can see is broken is the one outcome
    /// nobody can act on.
    /// </summary>
    [Fact]
    public async Task AnImportThatInvertsAHardStackDependencyIsAcceptedAndTheViolationRecorded()
    {
        var database = AddRepository("db");
        var backend = AddRepository("backend");
        AddStackDependency(
            from: AddStack("backend", backend),
            to: AddStack("database", database),
            StackDependencyType.Hard);

        var databaseMr = AddMergeRequest(database, externalId: "10");
        var backendMr = AddMergeRequest(backend, externalId: "20");
        await Db.SaveChangesAsync(Ct);

        // Backend first, database second — exactly backwards.
        var plan = await Planner().ImportFromYamlAsync(
            Yaml(Stage(1, "vcs:group/backend!20"), Stage(2, "vcs:group/db!10")), ct: Ct);

        Assert.Equal([backendMr.Id], StageItems(plan, 1));

        var conflict = Assert.Single(plan.Conflicts);
        Assert.Equal(nameof(Application.ReleasePlanning.PlanEdgeKind.StackHard), conflict.Kind);
        Assert.Equal(databaseMr.Id, conflict.FromMergeRequestId);
        Assert.Equal(backendMr.Id, conflict.ToMergeRequestId);
        Assert.Contains("db!10", conflict.Reason);
        Assert.Contains("backend!20", conflict.Reason);
    }

    [Fact]
    public async Task AnInvertedTaskDependencyIsRecordedToo()
    {
        var repo = AddRepository("api");
        var first = AddTask("TASK-1");
        var second = AddTask("TASK-2");
        AddTaskDependency(dependent: second, dependsOn: first);
        AddMergeRequest(repo, first, externalId: "10");
        AddMergeRequest(repo, second, externalId: "20");
        await Db.SaveChangesAsync(Ct);

        var plan = await Planner().ImportFromYamlAsync(
            Yaml(Stage(1, "vcs:group/api!20"), Stage(2, "vcs:group/api!10")), ct: Ct);

        var conflict = Assert.Single(plan.Conflicts);
        Assert.Equal(nameof(Application.ReleasePlanning.PlanEdgeKind.TaskDependency), conflict.Kind);
    }

    /// <summary>
    /// Two merge requests in the same stage deploy together, so a constraint between them is
    /// violated just as surely as by the wrong order. `predSeq >= seq`, not `>`.
    /// </summary>
    [Fact]
    public async Task BothSidesOfAConstraintInOneStageIsAViolation()
    {
        var repo = AddRepository("api");
        var first = AddTask("TASK-1");
        var second = AddTask("TASK-2");
        AddTaskDependency(dependent: second, dependsOn: first);
        AddMergeRequest(repo, first, externalId: "10");
        AddMergeRequest(repo, second, externalId: "20");
        await Db.SaveChangesAsync(Ct);

        var plan = await Planner().ImportFromYamlAsync(
            Yaml(Stage(1, "vcs:group/api!10", "vcs:group/api!20")), ct: Ct);

        Assert.Single(plan.Conflicts);
    }

    /// <summary>
    /// The recorded conflicts describe the plan as stored, so an import that honours everything
    /// must not carry any — otherwise "conflicts" degrades into decoration nobody reads.
    /// </summary>
    [Fact]
    public async Task AnImportThatHonoursEveryConstraintRecordsNoConflicts()
    {
        var repo = AddRepository("api");
        var first = AddTask("TASK-1");
        var second = AddTask("TASK-2");
        AddTaskDependency(dependent: second, dependsOn: first);
        AddMergeRequest(repo, first, externalId: "10");
        AddMergeRequest(repo, second, externalId: "20");
        await Db.SaveChangesAsync(Ct);

        var plan = await Planner().ImportFromYamlAsync(
            Yaml(Stage(1, "vcs:group/api!10"), Stage(2, "vcs:group/api!20")), ct: Ct);

        Assert.Empty(plan.Conflicts);
    }

    /// <summary>
    /// A soft link is advisory and the planner drops it itself to break cycles, so overriding one
    /// is not a violation and must not be recorded as a conflict — flagging the operator for a
    /// choice the planner makes unprompted would train them to ignore the list.
    /// </summary>
    [Fact]
    public async Task OverridingASoftStackDependencyIsNotAConflict()
    {
        var database = AddRepository("db");
        var backend = AddRepository("backend");
        AddStackDependency(
            from: AddStack("backend", backend),
            to: AddStack("database", database),
            StackDependencyType.Soft);

        AddMergeRequest(database, externalId: "10");
        var backendMr = AddMergeRequest(backend, externalId: "20");
        await Db.SaveChangesAsync(Ct);

        var plan = await Planner().ImportFromYamlAsync(
            Yaml(Stage(1, "vcs:group/backend!20"), Stage(2, "vcs:group/db!10")), ct: Ct);

        Assert.Equal([backendMr.Id], StageItems(plan, 1));
        Assert.Empty(plan.Conflicts);
    }

    /// <summary>
    /// A typo in an mr_id must not silently produce a plan missing a merge request — that is a
    /// deploy which looks complete and is not.
    /// </summary>
    [Fact]
    public async Task AnUnknownMergeRequestIsRejectedRatherThanDropped()
    {
        var repo = AddRepository("api");
        AddMergeRequest(repo, externalId: "10");
        await Db.SaveChangesAsync(Ct);

        var ex = await Assert.ThrowsAsync<DomainValidationException>(
            () => Planner().ImportFromYamlAsync(Yaml(Stage(1, "vcs:group/api!999")), ct: Ct));

        Assert.Contains("999", ex.Message);
    }

    [Fact]
    public async Task AnUnknownRepositoryIsRejected()
    {
        AddRepository("api");
        await Db.SaveChangesAsync(Ct);

        await Assert.ThrowsAsync<DomainValidationException>(
            () => Planner().ImportFromYamlAsync(Yaml(Stage(1, "vcs:group/ghost!10")), ct: Ct));
    }

    [Fact]
    public async Task ForceSkipsAnUnknownMergeRequestInsteadOfFailing()
    {
        var repo = AddRepository("api");
        var known = AddMergeRequest(repo, externalId: "10");
        await Db.SaveChangesAsync(Ct);

        var plan = await Planner().ImportFromYamlAsync(
            Yaml(Stage(1, "vcs:group/api!10", "vcs:group/api!999")), force: true, ct: Ct);

        var item = Assert.Single(plan.Stages.SelectMany(s => s.Items));
        Assert.Equal(known.Id, item.MergeRequestId);
    }

    [Theory]
    [InlineData("no-separators")]
    [InlineData("vcs:group/api")]      // no iid
    [InlineData("vcs:group/api!")]     // empty iid
    [InlineData(":group/api!10")]      // no connection
    [InlineData("a!b:c")]              // '!' before ':' — would slice a negative-length range
    public async Task AMalformedMrIdIsADomainErrorNotACrash(string mrId)
    {
        AddRepository("api");
        await Db.SaveChangesAsync(Ct);

        await Assert.ThrowsAsync<DomainValidationException>(
            () => Planner().ImportFromYamlAsync(Yaml(Stage(1, mrId)), ct: Ct));
    }

    /// <summary>
    /// Export exists to be edited and imported back. If a round trip does not survive, the feature
    /// is decorative — and this is the only test that runs both halves against each other.
    /// </summary>
    [Fact]
    public async Task AnExportedPlanCanBeImportedBackUnchanged()
    {
        var repo = AddRepository("api");
        var task = AddTask("TASK-1");
        var firstMr = AddMergeRequest(repo, task, externalId: "10");
        var secondMr = AddMergeRequest(repo, externalId: "20");
        await Db.SaveChangesAsync(Ct);

        var planner = Planner();
        var original = await planner.RecalculateAsync(Ct);
        var yaml = await planner.ExportToYamlAsync(original.Id, Ct);

        var reimported = await planner.ImportFromYamlAsync(yaml, ct: Ct);

        Assert.Equal(
            original.Stages.SelectMany(s => s.Items.Select(i => i.MergeRequestId)).OrderBy(id => id),
            reimported.Stages.SelectMany(s => s.Items.Select(i => i.MergeRequestId)).OrderBy(id => id));
        Assert.Contains(firstMr.Id, reimported.Stages.SelectMany(s => s.Items.Select(i => i.MergeRequestId)));
        Assert.Contains(secondMr.Id, reimported.Stages.SelectMany(s => s.Items.Select(i => i.MergeRequestId)));
    }

    [Fact]
    public async Task AnImportedStageIsMarkedAsAManualOverride()
    {
        var repo = AddRepository("api");
        AddMergeRequest(repo, externalId: "10");
        await Db.SaveChangesAsync(Ct);

        var plan = await Planner().ImportFromYamlAsync(Yaml(Stage(1, "vcs:group/api!10")), ct: Ct);

        Assert.True(plan.Stages.Single().IsManualOverride);
    }

    /// <summary>
    /// The hash is what lets an operator tell whether the stored plan is still the document they
    /// wrote. Storing it as null, or as the hash of something else, makes it worse than absent.
    /// </summary>
    [Fact]
    public async Task TheStoredHashIsTheHashOfTheSubmittedDocument()
    {
        var repo = AddRepository("api");
        AddMergeRequest(repo, externalId: "10");
        await Db.SaveChangesAsync(Ct);

        var yaml = Yaml(Stage(1, "vcs:group/api!10"));
        var plan = await Planner().ImportFromYamlAsync(yaml, ct: Ct);

        var stored = await Db.ReleasePlans.FindAsync([plan.Id], Ct);
        Assert.Equal(
            Infrastructure.ReleasePlanning.YamlReleasePlanSerializer.ComputeHash(yaml),
            stored!.YamlHash);
    }
}
