//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReleaseOrchestrator.Pwa.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReleaseOrchestrator.Pwa.Resources.UiStrings", typeof(UiStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string NotFound_Title {
            get {
                return ResourceManager.GetString("NotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there's nothing at this address..
        /// </summary>
        public static string NotFound_Message {
            get {
                return ResourceManager.GetString("NotFound_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Shell_Logout {
            get {
                return ResourceManager.GetString("Shell_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language_Label {
            get {
                return ResourceManager.GetString("Language_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking login state....
        /// </summary>
        public static string Auth_LoggingIn {
            get {
                return ResourceManager.GetString("Auth_LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing sign-in....
        /// </summary>
        public static string Auth_CompletingLoggingIn {
            get {
                return ResourceManager.GetString("Auth_CompletingLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not sign you in: {0}.
        /// </summary>
        public static string Auth_LogInFailed {
            get {
                return ResourceManager.GetString("Auth_LogInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing out....
        /// </summary>
        public static string Auth_LogOut {
            get {
                return ResourceManager.GetString("Auth_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing sign-out....
        /// </summary>
        public static string Auth_CompletingLogOut {
            get {
                return ResourceManager.GetString("Auth_CompletingLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not sign you out: {0}.
        /// </summary>
        public static string Auth_LogOutFailed {
            get {
                return ResourceManager.GetString("Auth_LogOutFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are signed out..
        /// </summary>
        public static string Auth_LogOutSucceeded {
            get {
                return ResourceManager.GetString("Auth_LogOutSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirecting to registration....
        /// </summary>
        public static string Auth_Registering {
            get {
                return ResourceManager.GetString("Auth_Registering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading your profile....
        /// </summary>
        public static string Auth_UserProfile {
            get {
                return ResourceManager.GetString("Auth_UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main navigation.
        /// </summary>
        public static string Nav_Aria {
            get {
                return ResourceManager.GetString("Nav_Aria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Plan.
        /// </summary>
        public static string Nav_ReleasePlan {
            get {
                return ResourceManager.GetString("Nav_ReleasePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML Editor.
        /// </summary>
        public static string Nav_YamlEditor {
            get {
                return ResourceManager.GetString("Nav_YamlEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Nav_Administration {
            get {
                return ResourceManager.GetString("Nav_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCS Connections.
        /// </summary>
        public static string Nav_VcsConnections {
            get {
                return ResourceManager.GetString("Nav_VcsConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker Connections.
        /// </summary>
        public static string Nav_TrackerConnections {
            get {
                return ResourceManager.GetString("Nav_TrackerConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string Nav_Repositories {
            get {
                return ResourceManager.GetString("Nav_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacks.
        /// </summary>
        public static string Nav_Stacks {
            get {
                return ResourceManager.GetString("Nav_Stacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Nav_Permissions {
            get {
                return ResourceManager.GetString("Nav_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Common_Save {
            get {
                return ResourceManager.GetString("Common_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Common_Add {
            get {
                return ResourceManager.GetString("Common_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Common_Create {
            get {
                return ResourceManager.GetString("Common_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved..
        /// </summary>
        public static string Common_Saved {
            get {
                return ResourceManager.GetString("Common_Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted..
        /// </summary>
        public static string Common_Deleted {
            get {
                return ResourceManager.GetString("Common_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Common_Name {
            get {
                return ResourceManager.GetString("Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Common_Type {
            get {
                return ResourceManager.GetString("Common_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API URL.
        /// </summary>
        public static string Common_ApiUrl {
            get {
                return ResourceManager.GetString("Common_ApiUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token.
        /// </summary>
        public static string Common_AccessToken {
            get {
                return ResourceManager.GetString("Common_AccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token (leave blank to keep current).
        /// </summary>
        public static string Common_AccessToken_Keep {
            get {
                return ResourceManager.GetString("Common_AccessToken_Keep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit {0}.
        /// </summary>
        public static string Common_Edit_Aria {
            get {
                return ResourceManager.GetString("Common_Edit_Aria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string Common_Delete_Aria {
            get {
                return ResourceManager.GetString("Common_Delete_Aria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Confirm_Delete_Title {
            get {
                return ResourceManager.GetString("Confirm_Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}? This cannot be undone..
        /// </summary>
        public static string Confirm_Delete_Message {
            get {
                return ResourceManager.GetString("Confirm_Delete_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not reach the server: {0}.
        /// </summary>
        public static string Error_Unreachable {
            get {
                return ResourceManager.GetString("Error_Unreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release Plan.
        /// </summary>
        public static string Plan_Title {
            get {
                return ResourceManager.GetString("Plan_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Release Plan.
        /// </summary>
        public static string Plan_Heading {
            get {
                return ResourceManager.GetString("Plan_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate.
        /// </summary>
        public static string Plan_Recalculate {
            get {
                return ResourceManager.GetString("Plan_Recalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export YAML.
        /// </summary>
        public static string Plan_ExportYaml {
            get {
                return ResourceManager.GetString("Plan_ExportYaml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active release plan.
        /// </summary>
        public static string Plan_Empty_Title {
            get {
                return ResourceManager.GetString("Plan_Empty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recalculate to build one from the merge requests that are ready to deploy..
        /// </summary>
        public static string Plan_Empty_Description {
            get {
                return ResourceManager.GetString("Plan_Empty_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} v{1} — {2} — updated {3}.
        /// </summary>
        public static string Plan_Meta {
            get {
                return ResourceManager.GetString("Plan_Meta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto-generated.
        /// </summary>
        public static string Plan_Meta_Auto {
            get {
                return ResourceManager.GetString("Plan_Meta_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manual.
        /// </summary>
        public static string Plan_Meta_Manual {
            get {
                return ResourceManager.GetString("Plan_Meta_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broken dependencies: {0}.
        /// </summary>
        public static string Plan_Conflicts_Title {
            get {
                return ResourceManager.GetString("Plan_Conflicts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The planner could not satisfy every constraint and ordered the stages anyway. Deploying in this order will violate the rules below — review before releasing..
        /// </summary>
        public static string Plan_Conflicts_Body {
            get {
                return ResourceManager.GetString("Plan_Conflicts_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage {0}.
        /// </summary>
        public static string Plan_Stage {
            get {
                return ResourceManager.GetString("Plan_Stage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Plan_Stage_Manual {
            get {
                return ResourceManager.GetString("Plan_Stage_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to drag to reorder.
        /// </summary>
        public static string Plan_Stage_DragHint {
            get {
                return ResourceManager.GetString("Plan_Stage_DragHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop a merge request here.
        /// </summary>
        public static string Plan_Stage_DropHint {
            get {
                return ResourceManager.GetString("Plan_Stage_DropHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add merge request.
        /// </summary>
        public static string Plan_AddMr {
            get {
                return ResourceManager.GetString("Plan_AddMr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added manually.
        /// </summary>
        public static string Plan_Item_ManualTooltip {
            get {
                return ResourceManager.GetString("Plan_Item_ManualTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from plan.
        /// </summary>
        public static string Plan_Item_Remove_Aria {
            get {
                return ResourceManager.GetString("Plan_Item_Remove_Aria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from plan.
        /// </summary>
        public static string Plan_Item_Remove_Title {
            get {
                return ResourceManager.GetString("Plan_Item_Remove_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0} !{1} from the release plan?.
        /// </summary>
        public static string Plan_Item_Remove_Message {
            get {
                return ResourceManager.GetString("Plan_Item_Remove_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add merge request to stage.
        /// </summary>
        public static string Plan_AddMr_Dialog_Title {
            get {
                return ResourceManager.GetString("Plan_AddMr_Dialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by branch or repository....
        /// </summary>
        public static string Plan_Filter_Placeholder {
            get {
                return ResourceManager.GetString("Plan_Filter_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string Plan_Col_Repository {
            get {
                return ResourceManager.GetString("Plan_Col_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Plan_Col_Branch {
            get {
                return ResourceManager.GetString("Plan_Col_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        public static string Plan_Col_Task {
            get {
                return ResourceManager.GetString("Plan_Col_Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan recalculated successfully..
        /// </summary>
        public static string Plan_Recalculated {
            get {
                return ResourceManager.GetString("Plan_Recalculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item moved..
        /// </summary>
        public static string Plan_ItemMoved {
            get {
                return ResourceManager.GetString("Plan_ItemMoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stages reordered..
        /// </summary>
        public static string Plan_StagesReordered {
            get {
                return ResourceManager.GetString("Plan_StagesReordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item removed..
        /// </summary>
        public static string Plan_ItemRemoved {
            get {
                return ResourceManager.GetString("Plan_ItemRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MR added to stage..
        /// </summary>
        public static string Plan_MrAdded {
            get {
                return ResourceManager.GetString("Plan_MrAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML Editor.
        /// </summary>
        public static string Yaml_Title {
            get {
                return ResourceManager.GetString("Yaml_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAML Release Plan.
        /// </summary>
        public static string Yaml_Heading {
            get {
                return ResourceManager.GetString("Yaml_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force import.
        /// </summary>
        public static string Yaml_ForceImport {
            get {
                return ResourceManager.GetString("Yaml_ForceImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Active.
        /// </summary>
        public static string Yaml_ExportActive {
            get {
                return ResourceManager.GetString("Yaml_ExportActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Yaml_Import {
            get {
                return ResourceManager.GetString("Yaml_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force skips validation against hard dependencies. The imported order may break them..
        /// </summary>
        public static string Yaml_ForceWarning {
            get {
                return ResourceManager.GetString("Yaml_ForceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste YAML here, or use 'Export Active' to load the current plan....
        /// </summary>
        public static string Yaml_Placeholder {
            get {
                return ResourceManager.GetString("Yaml_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active plan found..
        /// </summary>
        public static string Yaml_NoActivePlan {
            get {
                return ResourceManager.GetString("Yaml_NoActivePlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan '{0}' imported successfully..
        /// </summary>
        public static string Yaml_Imported {
            get {
                return ResourceManager.GetString("Yaml_Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCS Connections.
        /// </summary>
        public static string Vcs_Title {
            get {
                return ResourceManager.GetString("Vcs_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection.
        /// </summary>
        public static string Vcs_New {
            get {
                return ResourceManager.GetString("Vcs_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready-for-deploy label.
        /// </summary>
        public static string Vcs_Col_ReadyLabel {
            get {
                return ResourceManager.GetString("Vcs_Col_ReadyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        public static string Vcs_Label_Disabled {
            get {
                return ResourceManager.GetString("Vcs_Label_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit VCS Connection.
        /// </summary>
        public static string Vcs_Dialog_Edit {
            get {
                return ResourceManager.GetString("Vcs_Dialog_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New VCS Connection.
        /// </summary>
        public static string Vcs_Dialog_New {
            get {
                return ResourceManager.GetString("Vcs_Dialog_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge requests carrying this {0} label are picked up into the release plan automatically. Leave blank to turn that off — merge requests from this connection will then only enter a plan when added by hand..
        /// </summary>
        public static string Vcs_ReadyLabel_Helper {
            get {
                return ResourceManager.GetString("Vcs_ReadyLabel_Helper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCS connection '{0}'.
        /// </summary>
        public static string Vcs_Delete_What {
            get {
                return ResourceManager.GetString("Vcs_Delete_What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracker Connections.
        /// </summary>
        public static string Tracker_Title {
            get {
                return ResourceManager.GetString("Tracker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection.
        /// </summary>
        public static string Tracker_New {
            get {
                return ResourceManager.GetString("Tracker_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org ID.
        /// </summary>
        public static string Tracker_Col_OrgId {
            get {
                return ResourceManager.GetString("Tracker_Col_OrgId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tracker Connection.
        /// </summary>
        public static string Tracker_Dialog_Edit {
            get {
                return ResourceManager.GetString("Tracker_Dialog_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tracker Connection.
        /// </summary>
        public static string Tracker_Dialog_New {
            get {
                return ResourceManager.GetString("Tracker_Dialog_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Org ID (optional).
        /// </summary>
        public static string Tracker_OrgId_Label {
            get {
                return ResourceManager.GetString("Tracker_OrgId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yandex organization ID.
        /// </summary>
        public static string Tracker_OrgId_Placeholder {
            get {
                return ResourceManager.GetString("Tracker_OrgId_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tracker connection '{0}'.
        /// </summary>
        public static string Tracker_Delete_What {
            get {
                return ResourceManager.GetString("Tracker_Delete_What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string Repos_Title {
            get {
                return ResourceManager.GetString("Repos_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Repository.
        /// </summary>
        public static string Repos_New {
            get {
                return ResourceManager.GetString("Repos_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External ID.
        /// </summary>
        public static string Repos_Col_ExternalId {
            get {
                return ResourceManager.GetString("Repos_Col_ExternalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCS Connection.
        /// </summary>
        public static string Repos_Col_Connection {
            get {
                return ResourceManager.GetString("Repos_Col_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitLab project ID or path.
        /// </summary>
        public static string Repos_ExternalId_Placeholder {
            get {
                return ResourceManager.GetString("Repos_ExternalId_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository created..
        /// </summary>
        public static string Repos_Created {
            get {
                return ResourceManager.GetString("Repos_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to repository '{0}'.
        /// </summary>
        public static string Repos_Delete_What {
            get {
                return ResourceManager.GetString("Repos_Delete_What", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stacks.
        /// </summary>
        public static string Stacks_Title {
            get {
                return ResourceManager.GetString("Stacks_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Stack.
        /// </summary>
        public static string Stacks_New {
            get {
                return ResourceManager.GetString("Stacks_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string Stacks_Dependencies {
            get {
                return ResourceManager.GetString("Stacks_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string Stacks_Repositories {
            get {
                return ResourceManager.GetString("Stacks_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Dependency.
        /// </summary>
        public static string Stacks_AddDependency {
            get {
                return ResourceManager.GetString("Stacks_AddDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Stack.
        /// </summary>
        public static string Stacks_TargetStack {
            get {
                return ResourceManager.GetString("Stacks_TargetStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Repository.
        /// </summary>
        public static string Stacks_AssignRepository {
            get {
                return ResourceManager.GetString("Stacks_AssignRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string Stacks_Repository {
            get {
                return ResourceManager.GetString("Stacks_Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        public static string Stacks_Assign {
            get {
                return ResourceManager.GetString("Stacks_Assign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Stack.
        /// </summary>
        public static string Stacks_Dialog_New {
            get {
                return ResourceManager.GetString("Stacks_Dialog_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack Name.
        /// </summary>
        public static string Stacks_Name {
            get {
                return ResourceManager.GetString("Stacks_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack created..
        /// </summary>
        public static string Stacks_Created {
            get {
                return ResourceManager.GetString("Stacks_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency added..
        /// </summary>
        public static string Stacks_DependencyAdded {
            get {
                return ResourceManager.GetString("Stacks_DependencyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository assigned..
        /// </summary>
        public static string Stacks_RepositoryAssigned {
            get {
                return ResourceManager.GetString("Stacks_RepositoryAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Perms_Title {
            get {
                return ResourceManager.GetString("Perms_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Claims.
        /// </summary>
        public static string Perms_Claims_Title {
            get {
                return ResourceManager.GetString("Perms_Claims_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No permission claims defined..
        /// </summary>
        public static string Perms_Claims_Empty {
            get {
                return ResourceManager.GetString("Perms_Claims_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Mappings.
        /// </summary>
        public static string Perms_Mappings_Title {
            get {
                return ResourceManager.GetString("Perms_Mappings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Mapping.
        /// </summary>
        public static string Perms_AddMapping {
            get {
                return ResourceManager.GetString("Perms_AddMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AD Group SID.
        /// </summary>
        public static string Perms_Sid {
            get {
                return ResourceManager.GetString("Perms_Sid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission Claim.
        /// </summary>
        public static string Perms_Claim {
            get {
                return ResourceManager.GetString("Perms_Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim.
        /// </summary>
        public static string Perms_Col_Claim {
            get {
                return ResourceManager.GetString("Perms_Col_Claim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No group mappings configured..
        /// </summary>
        public static string Perms_Mappings_Empty {
            get {
                return ResourceManager.GetString("Perms_Mappings_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove {0}.
        /// </summary>
        public static string Perms_Remove_Aria {
            get {
                return ResourceManager.GetString("Perms_Remove_Aria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove mapping.
        /// </summary>
        public static string Perms_Remove_Title {
            get {
                return ResourceManager.GetString("Perms_Remove_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove '{0}' from group {1}? This cannot be undone..
        /// </summary>
        public static string Perms_Remove_Message {
            get {
                return ResourceManager.GetString("Perms_Remove_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping added..
        /// </summary>
        public static string Perms_MappingAdded {
            get {
                return ResourceManager.GetString("Perms_MappingAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping removed..
        /// </summary>
        public static string Perms_MappingRemoved {
            get {
                return ResourceManager.GetString("Perms_MappingRemoved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Nav_Tasks {
            get {
                return ResourceManager.GetString("Nav_Tasks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks_Title {
            get {
                return ResourceManager.GetString("Tasks_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Tasks_Heading {
            get {
                return ResourceManager.GetString("Tasks_Heading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No tasks yet.
        /// </summary>
        public static string Tasks_Empty_Title {
            get {
                return ResourceManager.GetString("Tasks_Empty_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tasks appear here once they are ingested from a tracker..
        /// </summary>
        public static string Tasks_Empty_Description {
            get {
                return ResourceManager.GetString("Tasks_Empty_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Tasks_Col_Key {
            get {
                return ResourceManager.GetString("Tasks_Col_Key", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Tasks_Col_Title {
            get {
                return ResourceManager.GetString("Tasks_Col_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Tasks_Col_Status {
            get {
                return ResourceManager.GetString("Tasks_Col_Status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MRs.
        /// </summary>
        public static string Tasks_Col_Mrs {
            get {
                return ResourceManager.GetString("Tasks_Col_Mrs", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Tasks_Col_Plan {
            get {
                return ResourceManager.GetString("Tasks_Col_Plan", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Built.
        /// </summary>
        public static string Tasks_PlanBuilt {
            get {
                return ResourceManager.GetString("Tasks_PlanBuilt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Tasks_PlanNone {
            get {
                return ResourceManager.GetString("Tasks_PlanNone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Tasks_Open {
            get {
                return ResourceManager.GetString("Tasks_Open", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back to tasks.
        /// </summary>
        public static string TaskDetail_Back {
            get {
                return ResourceManager.GetString("TaskDetail_Back", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recalculate plan.
        /// </summary>
        public static string TaskDetail_Recalculate {
            get {
                return ResourceManager.GetString("TaskDetail_Recalculate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plan recalculated..
        /// </summary>
        public static string TaskDetail_Recalculated {
            get {
                return ResourceManager.GetString("TaskDetail_Recalculated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No plan yet.
        /// </summary>
        public static string TaskDetail_NoPlan_Title {
            get {
                return ResourceManager.GetString("TaskDetail_NoPlan_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Recalculate to build the rollout plan for this task..
        /// </summary>
        public static string TaskDetail_NoPlan_Description {
            get {
                return ResourceManager.GetString("TaskDetail_NoPlan_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Build plan.
        /// </summary>
        public static string TaskDetail_Build {
            get {
                return ResourceManager.GetString("TaskDetail_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version {0}, source {1}, updated {2}.
        /// </summary>
        public static string TaskDetail_Meta {
            get {
                return ResourceManager.GetString("TaskDetail_Meta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dependency tree.
        /// </summary>
        public static string TaskDetail_Tree_Title {
            get {
                return ResourceManager.GetString("TaskDetail_Tree_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Execution waves.
        /// </summary>
        public static string TaskDetail_Waves_Title {
            get {
                return ResourceManager.GetString("TaskDetail_Waves_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to target.
        /// </summary>
        public static string TaskDetail_Target {
            get {
                return ResourceManager.GetString("TaskDetail_Target", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No merge requests.
        /// </summary>
        public static string TaskDetail_NoItems {
            get {
                return ResourceManager.GetString("TaskDetail_NoItems", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to depends on.
        /// </summary>
        public static string TaskDetail_DependsOn {
            get {
                return ResourceManager.GetString("TaskDetail_DependsOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wave {0}.
        /// </summary>
        public static string Plan_Wave {
            get {
                return ResourceManager.GetString("Plan_Wave", resourceCulture);
            }
        }

    }
}
