namespace ReleaseOrchestrator.Application.DTOs;

public record ReleasePlanDto(
    Guid Id,
    string Name,
    string Version,
    bool IsActive,
    bool AutoGenerated,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    IReadOnlyList<ReleaseStageDto> Stages);

public record ReleaseStageDto(
    Guid Id,
    int Sequence,
    string? Name,
    bool IsManualOverride,
    IReadOnlyList<StageItemDto> Items);

public record StageItemDto(
    Guid Id,
    Guid MergeRequestId,
    bool ManualInclusion,
    string MrExternalId,
    string MrSourceBranch,
    string MrTargetBranch,
    string RepositoryName,
    string? TaskExternalId,
    string MrStatus);
