namespace ReleaseOrchestrator.Application.DTOs;

public record ReleasePlanDto(
    Guid Id,
    string Name,
    string Version,
    bool IsActive,
    bool AutoGenerated,
    DateTime CreatedAt,
    DateTime UpdatedAt,
    IReadOnlyList<ReleaseStageDto> Stages,
    IReadOnlyList<PlanConflictDto> Conflicts);

/// <summary>
/// A dependency the plan could not honour. A non-empty list means the stage order
/// violates a declared constraint — operators must see this, never a silent plan.
/// </summary>
public record PlanConflictDto(
    string Kind,
    Guid FromMergeRequestId,
    Guid ToMergeRequestId,
    string Reason);

public record ReleaseStageDto(
    Guid Id,
    int Sequence,
    string? Name,
    bool IsManualOverride,
    IReadOnlyList<StageItemDto> Items);

public record StageItemDto(
    Guid Id,
    Guid MergeRequestId,
    bool ManualInclusion,
    string MrExternalId,
    string MrSourceBranch,
    string MrTargetBranch,
    string RepositoryName,
    string? TaskExternalId,
    string MrStatus);
