namespace ReleaseOrchestrator.Core.Entities;

public class ReleasePlan
{
    public Guid Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Version { get; set; } = string.Empty;
    public bool IsActive { get; set; }
    public bool AutoGenerated { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
    public string? YamlHash { get; set; }

    public ICollection<ReleaseStage> Stages { get; set; } = [];
}
