using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReleaseOrchestrator.Infrastructure.Persistence.Models;

/// <summary>An ordered set of stages: what deploys, and in what order.</summary>
/// <remarks>
/// At most one plan is active at a time, enforced by a filtered unique index on
/// <see cref="IsActive"/>. That index cannot be declared here — <c>[Index]</c> has no filter — so
/// it lives in <see cref="AppDbContext.OnModelCreating"/>, which is the only mapping in this model
/// that does.
/// </remarks>
[Index(nameof(CreatedAt), Name = "IX_ReleasePlan_CreatedAt")]
public class ReleasePlan
{
    /// <summary>Primary key.</summary>
    [Key]
    public Guid Id { get; set; }

    /// <summary>Operator-facing name.</summary>
    [Required, MaxLength(300)]
    public string Name { get; set; } = string.Empty;

    /// <summary>Version label. Generated plans stamp the time they were built.</summary>
    [Required, MaxLength(50)]
    public string Version { get; set; } = string.Empty;

    /// <summary>The one plan in force. See the filtered unique index on the type.</summary>
    public bool IsActive { get; set; }

    /// <summary>False when an operator imported it. An imported plan outranks a generated one.</summary>
    public bool AutoGenerated { get; set; }

    /// <summary>When the plan was stored.</summary>
    public DateTime CreatedAt { get; set; }

    /// <summary>When it was last edited.</summary>
    public DateTime UpdatedAt { get; set; }

    /// <summary>SHA-256 of the imported document, so an operator can tell whether this is still what they wrote.</summary>
    [MaxLength(64)]
    public string? YamlHash { get; set; }

    /// <summary>
    /// When the planner began reading the data this plan was built from. A recalculation
    /// request raised before this instant is already reflected here and can be skipped;
    /// one raised after it is not. Comparing against <see cref="CreatedAt"/> instead would
    /// drop changes committed while the plan was being computed.
    /// </summary>
    public DateTime SnapshotStartedAt { get; set; }

    /// <summary>
    /// Ordering constraints this plan does not honour, as JSON. Null means it honours every one.
    /// A plan may break a constraint — an operator sometimes has to deploy against the declared
    /// order — but it may never report itself clean while doing so, which is what this column is for.
    /// </summary>
    public string? ConflictsJson { get; set; }

    /// <summary>Its stages, in <see cref="ReleaseStage.Sequence"/> order.</summary>
    [InverseProperty(nameof(ReleaseStage.Plan))]
    public ICollection<ReleaseStage> Stages { get; set; } = [];
}
