// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ReleaseOrchestrator.Infrastructure.Persistence;

#nullable disable

namespace ReleaseOrchestrator.Migrations.Postgres.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260726180712_RetireReadyForDeployLabel")]
    partial class RetireReadyForDeployLabel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.ActionBinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Scope")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EventType" }, "IX_ActionBinding_EventType");

                    b.ToTable("ActionBindings");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.DeploymentEnvironment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReadinessRuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ReadinessRuleId");

                    b.HasIndex(new[] { "Key" }, "IX_DeploymentEnvironment_Key")
                        .IsUnique();

                    b.ToTable("DeploymentEnvironments");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.GroupPermissionMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdGroupSid")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PermissionClaimId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionClaimId");

                    b.HasIndex(new[] { "AdGroupSid", "PermissionClaimId" }, "IX_GroupPermissionMapping_AdGroupSid_PermissionClaimId")
                        .IsUnique();

                    b.ToTable("GroupPermissionMappings");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsStatusManual")
                        .HasColumnType("boolean");

                    b.Property<string>("Labels")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("MergedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TargetBranch")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TaskExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ClosedAt" }, "IX_MergeRequest_ClosedAt");

                    b.HasIndex(new[] { "MergedAt" }, "IX_MergeRequest_MergedAt");

                    b.HasIndex(new[] { "RepositoryId", "ExternalId" }, "IX_MergeRequest_RepositoryId_ExternalId")
                        .IsUnique();

                    b.HasIndex(new[] { "RepositoryId", "Status" }, "IX_MergeRequest_RepositoryId_Status");

                    b.HasIndex(new[] { "Status" }, "IX_MergeRequest_Status");

                    b.HasIndex(new[] { "TaskExternalId" }, "IX_MergeRequest_TaskExternalId");

                    b.HasIndex(new[] { "TaskId" }, "IX_MergeRequest_TaskId");

                    b.ToTable("MergeRequests");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequestLabelChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ActorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorOid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FromLabels")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("MergeRequestExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToLabels")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MergeRequestId", "At" }, "IX_MergeRequestLabelChange_MergeRequestId_At");

                    b.HasIndex(new[] { "TaskId", "At" }, "IX_MergeRequestLabelChange_TaskId_At");

                    b.ToTable("MergeRequestLabelChanges");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequestReadinessPin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ActorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorOid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex(new[] { "MergeRequestId", "EnvironmentId" }, "IX_MergeRequestReadinessPin_Mr_Environment")
                        .IsUnique();

                    b.ToTable("MergeRequestReadinessPins");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequestStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ActorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorOid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MergeRequestExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MergeRequestId", "At" }, "IX_MergeRequestStatusChange_MergeRequestId_At");

                    b.HasIndex(new[] { "TaskId", "At" }, "IX_MergeRequestStatusChange_TaskId_At");

                    b.ToTable("MergeRequestStatusChanges");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MrDeployClaim", b =>
                {
                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("OwnerRolloutId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("MergeRequestId", "EnvironmentId");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("MrDeployClaims");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MrDeploymentState", b =>
                {
                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("MergeRequestId", "EnvironmentId");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("MrDeploymentStates");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PermissionClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("PermissionClaims");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeployStrategyKeyOverride")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("IntraTaskOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("ManualInclusion")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanTaskNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "MergeRequestId" }, "IX_PlanItem_MergeRequestId");

                    b.HasIndex(new[] { "PlanTaskNodeId", "MergeRequestId" }, "IX_PlanItem_Node_Mr")
                        .IsUnique();

                    b.ToTable("PlanItems");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RolloutPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RolloutPlanId");

                    b.ToTable("PlanOverrides");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanTaskNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RolloutPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex(new[] { "RolloutPlanId", "TaskId" }, "IX_PlanTaskNode_Plan_Task")
                        .IsUnique();

                    b.ToTable("PlanTaskNodes");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.ProcessedEvent", b =>
                {
                    b.Property<string>("Source")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EventId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Source", "EventId");

                    b.ToTable("ProcessedEvents");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.ReadinessRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequiredSignals")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "IX_ReadinessRule_Name")
                        .IsUnique();

                    b.ToTable("ReadinessRules");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConnectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeployStrategyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DeployStrategySettingsJson")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("TrackerConnectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TrackerConnectionId");

                    b.HasIndex(new[] { "ConnectionId", "ExternalId" }, "IX_Repository_ConnectionId_ExternalId")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RepositoryDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromRepositoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ToRepositoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ToRepositoryId");

                    b.HasIndex(new[] { "FromRepositoryId", "ToRepositoryId" }, "IX_RepositoryDependency_From_To")
                        .IsUnique();

                    b.ToTable("RepositoryDependencies");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RepositoryDeployTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeploySettingsJson")
                        .HasColumnType("text");

                    b.Property<string>("DeployStrategyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ReadinessRuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("RedeployPolicy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("ReadinessRuleId");

                    b.HasIndex(new[] { "RepositoryId", "EnvironmentId" }, "IX_RepositoryDeployTarget_Repository_Environment")
                        .IsUnique();

                    b.ToTable("RepositoryDeployTargets");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Rollout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LaunchedByKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("LaunchedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("LaunchedByOid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PlanSnapshotJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RolloutPlanId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetTaskId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("EnvironmentId");

                    b.HasIndex("RolloutPlanId");

                    b.HasIndex("TargetTaskId", "EnvironmentId")
                        .IsUnique()
                        .HasDatabaseName("IX_Rollout_TargetTask_Environment_Live")
                        .HasFilter("\"Status\" <> 5 AND \"Status\" <> 6 AND \"Status\" <> 7");

                    b.HasIndex(new[] { "IdempotencyKey" }, "IX_Rollout_IdempotencyKey")
                        .IsUnique();

                    b.HasIndex(new[] { "TargetTaskId" }, "IX_Rollout_TargetTaskId");

                    b.ToTable("Rollouts");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ActorName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ActorOid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PayloadJson")
                        .HasColumnType("text");

                    b.Property<Guid>("RolloutId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RolloutId");

                    b.ToTable("RolloutEvents");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConflictsJson")
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByKind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("CreatedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CreatedByOid")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("SnapshotStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetTaskId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("YamlHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("TargetTaskId")
                        .IsUnique()
                        .HasDatabaseName("IX_RolloutPlan_TargetTaskId_Active")
                        .HasFilter("\"IsActive\"");

                    b.HasIndex(new[] { "CreatedAt" }, "IX_RolloutPlan_CreatedAt");

                    b.HasIndex(new[] { "TargetTaskId", "CreatedAt" }, "IX_RolloutPlan_TargetTaskId_CreatedAt");

                    b.ToTable("RolloutPlans");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("DeploySettingsJson")
                        .HasColumnType("text");

                    b.Property<string>("DeployStrategyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ExternalRef")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("MergeShaAtSnapshot")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RolloutId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<int>("Wave")
                        .HasColumnType("integer");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("MergeRequestId");

                    b.HasIndex("TaskId");

                    b.HasIndex(new[] { "RolloutId", "MergeRequestId" }, "IX_RolloutStep_Rollout_Mr")
                        .IsUnique();

                    b.ToTable("RolloutSteps");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutStepAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("At")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AttemptNo")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("RolloutStepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RolloutStepId");

                    b.ToTable("RolloutStepAttempts");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskDependency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DependentTaskId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DependsOnTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DependsOnTaskId");

                    b.HasIndex(new[] { "DependentTaskId", "DependsOnTaskId" }, "IX_TaskDependency_Dependent_DependsOn")
                        .IsUnique();

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstSeenSource")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentTaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TrackerConnectionId")
                        .HasColumnType("uuid");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("ParentTaskId");

                    b.HasIndex(new[] { "ClosedAt" }, "IX_TaskItem_ClosedAt");

                    b.HasIndex(new[] { "ExternalId" }, "IX_TaskItem_ExternalId");

                    b.HasIndex(new[] { "TrackerConnectionId", "ExternalId" }, "IX_TaskItem_TrackerConnectionId_ExternalId")
                        .IsUnique();

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TrackerConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderSettingsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_TrackerConnection_Name")
                        .IsUnique();

                    b.ToTable("TrackerConnections");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.UserPermissionOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionClaimId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionClaimId");

                    b.HasIndex(new[] { "UserId", "PermissionClaimId" }, "IX_UserPermissionOverride_UserId_PermissionClaimId")
                        .IsUnique();

                    b.ToTable("UserPermissionOverrides");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.VcsConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<byte[]>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProviderSettingsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Name" }, "UQ_VcsConnection_Name")
                        .IsUnique();

                    b.ToTable("VcsConnections");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.DeploymentEnvironment", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.ReadinessRule", "ReadinessRule")
                        .WithMany("Environments")
                        .HasForeignKey("ReadinessRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ReadinessRule");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.GroupPermissionMapping", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.PermissionClaim", "PermissionClaim")
                        .WithMany("GroupMappings")
                        .HasForeignKey("PermissionClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionClaim");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", "Repository")
                        .WithMany("MergeRequests")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "Task")
                        .WithMany("MergeRequests")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Repository");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequestReadinessPin", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.DeploymentEnvironment", "Environment")
                        .WithMany("ReadinessPins")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");

                    b.Navigation("MergeRequest");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MrDeployClaim", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.DeploymentEnvironment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Environment");

                    b.Navigation("MergeRequest");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.MrDeploymentState", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.DeploymentEnvironment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Environment");

                    b.Navigation("MergeRequest");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanItem", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanTaskNode", "PlanTaskNode")
                        .WithMany("Items")
                        .HasForeignKey("PlanTaskNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MergeRequest");

                    b.Navigation("PlanTaskNode");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanOverride", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", "RolloutPlan")
                        .WithMany("Overrides")
                        .HasForeignKey("RolloutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolloutPlan");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanTaskNode", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", "RolloutPlan")
                        .WithMany("Nodes")
                        .HasForeignKey("RolloutPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RolloutPlan");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.VcsConnection", "Connection")
                        .WithMany("Repositories")
                        .HasForeignKey("ConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TrackerConnection", "TrackerConnection")
                        .WithMany("Repositories")
                        .HasForeignKey("TrackerConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Connection");

                    b.Navigation("TrackerConnection");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RepositoryDependency", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", "FromRepository")
                        .WithMany("DependsOn")
                        .HasForeignKey("FromRepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", "ToRepository")
                        .WithMany("RequiredBy")
                        .HasForeignKey("ToRepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromRepository");

                    b.Navigation("ToRepository");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RepositoryDeployTarget", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.DeploymentEnvironment", "Environment")
                        .WithMany("DeployTargets")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.ReadinessRule", "ReadinessRule")
                        .WithMany("DeployTargets")
                        .HasForeignKey("ReadinessRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", "Repository")
                        .WithMany("DeployTargets")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Environment");

                    b.Navigation("ReadinessRule");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Rollout", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.DeploymentEnvironment", "Environment")
                        .WithMany()
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", "RolloutPlan")
                        .WithMany()
                        .HasForeignKey("RolloutPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "TargetTask")
                        .WithMany()
                        .HasForeignKey("TargetTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Environment");

                    b.Navigation("RolloutPlan");

                    b.Navigation("TargetTask");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutEvent", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Rollout", "Rollout")
                        .WithMany()
                        .HasForeignKey("RolloutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rollout");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "TargetTask")
                        .WithMany()
                        .HasForeignKey("TargetTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TargetTask");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutStep", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.MergeRequest", "MergeRequest")
                        .WithMany()
                        .HasForeignKey("MergeRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.Rollout", "Rollout")
                        .WithMany("Steps")
                        .HasForeignKey("RolloutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MergeRequest");

                    b.Navigation("Rollout");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutStepAttempt", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutStep", "RolloutStep")
                        .WithMany("Attempts")
                        .HasForeignKey("RolloutStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RolloutStep");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskDependency", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "DependentTask")
                        .WithMany("Dependencies")
                        .HasForeignKey("DependentTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "DependsOnTask")
                        .WithMany("Dependents")
                        .HasForeignKey("DependsOnTaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DependentTask");

                    b.Navigation("DependsOnTask");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", "ParentTask")
                        .WithMany("Children")
                        .HasForeignKey("ParentTaskId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.TrackerConnection", "TrackerConnection")
                        .WithMany("Tasks")
                        .HasForeignKey("TrackerConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentTask");

                    b.Navigation("TrackerConnection");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.UserPermissionOverride", b =>
                {
                    b.HasOne("ReleaseOrchestrator.Infrastructure.Persistence.Models.PermissionClaim", "PermissionClaim")
                        .WithMany("UserOverrides")
                        .HasForeignKey("PermissionClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionClaim");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.DeploymentEnvironment", b =>
                {
                    b.Navigation("DeployTargets");

                    b.Navigation("ReadinessPins");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PermissionClaim", b =>
                {
                    b.Navigation("GroupMappings");

                    b.Navigation("UserOverrides");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.PlanTaskNode", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.ReadinessRule", b =>
                {
                    b.Navigation("DeployTargets");

                    b.Navigation("Environments");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Repository", b =>
                {
                    b.Navigation("DependsOn");

                    b.Navigation("DeployTargets");

                    b.Navigation("MergeRequests");

                    b.Navigation("RequiredBy");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.Rollout", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutPlan", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("Overrides");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.RolloutStep", b =>
                {
                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TaskItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Dependencies");

                    b.Navigation("Dependents");

                    b.Navigation("MergeRequests");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.TrackerConnection", b =>
                {
                    b.Navigation("Repositories");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("ReleaseOrchestrator.Infrastructure.Persistence.Models.VcsConnection", b =>
                {
                    b.Navigation("Repositories");
                });
#pragma warning restore 612, 618
        }
    }
}
